---
apiVersion: v2
appVersion: 1.2.7
description: IPMI Server
name: ipmi-server
version: 0.2.0
kubeVersion: '>=1.32.0-0'
keywords:
  - ipmi
home: https://github.com/reitermarkus/helm-charts/tree/main/charts/ipmi-server
sources:
  - https://github.com/mneveroff/ipmi-server
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
