---
apiVersion: v2
appVersion: 5.1.1
description: openHAB - a vendor and technology agnostic open source automation software for your home
name: openhab
version: 6.5.1
kubeVersion: ">=1.16.0-0"
keywords:
  - openhab
  - home-automation
home: https://github.com/reitermarkus/helm-charts/tree/main/charts/openhab
icon: https://www.openhab.org/openhab-logo-square.png
sources:
  - https://www.openhab.org
  - https://hub.docker.com/r/openhab/openhab
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.5.0
