---
{{- include "bjw-s.common.loader.init" . }}

{{- define "ipmi-server.harcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{- if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "ipmi-server.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
